# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('text_content', models.CharField(max_length=20000)),
                ('text_createTime', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.CreateModel(
            name='User_Vocie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('voice_name', models.CharField(max_length=1000)),
                ('voice_path', models.CharField(max_length=5000)),
                ('vocie_createTime', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
    ]
